### ISSUE TITLE
Test: infocontagion/model.find_optimum(agent)

### ISSUE THREAD

**Issue by cogeorg** [cogeorg/econlib#10]
Write a test to ensure that infocontagion/model.find_optimum(agent) computes the correct optimum. To do that, do the following:
1. Write an additional routine calculate_EU_test(agent) that has the same signature as the calculate_EU1(agent) etc. routines but has a more simple result. Use e.g. a function that finds the highest value for EU for a specific value of each parameter (we iterate over 5 parameters).
2. Check the code carefully that there are no typos.

**Comment by pafiedor** [comment]
In commit ef897cf0b24c8f136d84b376165eec98906a33b8 there's calculate_EU_test(), it's simple but shows that the code works, most notably by changing signs in the sum it find the correct border of the domain. Doesn't appear there are any typos in there that I could find.
