### ISSUE TITLE
Debug infocontagion/model.py expected utilities

### ISSUE THREAD

**Issue by cogeorg** [cogeorg/econlib#11]
I need a fresh pair of eyes to make sure there is no typo in the formulas for the expected utility I programmed. Therefore, check http://papers.ssrn.com/sol3/papers.cfm?abstract_id=2625575 and compare the formulas for the different EUs with the code written in the different calculate_EU*(agent) routines in infocontagion/model.py. 

In a second step, double-check that the formulas programmed in expected_utility_*(agent) correspond to the formulas derived in the paper. In particular:
expected_utility_H <--> (4) 
expected_utility_1L <--> (6)
expected_utility_2L <--> (12)
expected_utility_5 <--> (17)
expected_utility_6 <--> (19)

For the check, you also need to double-check the different thetas. 

This is not a trivial issue, please think a bit about how we could ensure that the programming of the different expected utilities corresponds exactly to what is written in the paper. Later, we will need to generalize this, because it is a common problem and many of the expected utilities are even more complicated than the ones I have implemented here.

**Comment by pafiedor** [comment]
I looked through the code multiple times, looks consistent with the paper for expected utilities, utilities, and thetas. I think there's no good way to ensure it's correct a priori, just checking the code a few times. If some properties of these measures are known they can be simulated/graphed.
