### ISSUE TITLE
Test: Make sure initialization of all classes works properly

### ISSUE THREAD

**Issue by cogeorg** [cogeorg/econlib#12]
In infocontagion/runner.do_run() we iterate over a set of simulations. For each simulation, we need to initialize a fresh set of agents and a new model configuration (do_run() generates a new model parameter set based on the runner_config.xml and model_config.xml). This has proven to be error-prone in the past, so please write a test (or any other code) that ensures that the model and all agents are properly initialized.

**Comment by pafiedor** [comment]
In ef897cf0b24c8f136d84b376165eec98906a33b8 there are do_run_test_verbose() and do_run_test_silent(), I've ran these a few times, and appears that everything is initialized as it should. For the silent one I've just copied values by hand to the code, reading the config and then reading the config again and checking if the two are the same seems slightly counterproductive to me, but we can in principle code another read config and compare with the initialized one.
