### ISSUE TITLE
Check limiting cases 

### ISSUE THREAD

**Issue by cogeorg** [cogeorg/econlib#14]
In the Ahnert/Georg Information Contagion paper there is a section on limiting cases where we discuss what results the code should deliver for certain, simple parameter choices. Please double-check that these are actually reproduced.

**Comment by pafiedor** [comment]
I've ran these, and most look the same as in the table B.1, but a couple are slightly different:
-in the case of phi=0 it's 0.1 for all baseline setups when I ran it
-for lambda=0.01 they're slightly different too:
*baseline1: y=0.52 not 0.42
*baseline2: y=0.45 not 0.36
*baseline3: y=0.6 not 0.48
*baseline4: y=0.65 not 0.74 & d1=1.05 not 1.16

Additionally, rho equal exactly 1 seems to break down the simulation, anything arbitraly close to 1 works fine though.
