### ISSUE TITLE
mappingtools.tuple_to_string ist useless

### ISSUE THREAD

**Issue by Michael-E-Rose** [cogeorg/econlib#16]
Function `tuple_to_string` in [`mappingtools.py`](https://github.com/cogeorg/econlib/blob/master/src/mappingtools.py) is useless. It combines all elements of a tuple to a simple string. However, it is overly complicated as one can simply use `.join()`:

    >>> x = ("k", "m")
    >>> "_".join(x)
    'k_m'

Can I safely remove it, @cogeorg?

**Comment by Michael-E-Rose** [comment]
@cogeorg: I would like to remove this useless method. If you are using it: Can you please update your scripts (i.e., use the `join()` method)?

**Comment by cogeorg** [comment]
I am not updating nothing. But I will if the method is gone. Why not simply keep the interface and just replace the content? I like the method because it makes my code more readable.
