### ISSUE TITLE
Methods read_output_one() and read_output_mult() in abmtools.py

### ISSUE THREAD

**Issue by Michael-E-Rose** [cogeorg/econlib#18]
Hi @pafiedor! In dc876a71c928fdb355fa485a4d7c1dfdbe124ada I improved [`src/abmtools.py`](https://github.com/cogeorg/econlib/blob/master/src/abmtools.py) a little bit. I hope that's okay. I've seen that `read_output_one()` and `read_output_mult()` are the same. Is this intended?

Also, if you are interested in just one row of a file, you're faster with `pandas`:

    import pandas as pd
    df = pd.read_csv(inf)
    my_row = df['my_row']
    my_list = my_row.tolist()

or simply

    import pandas as pd
    my_list = pd.read_csv(inf)['my_row'].tolist()

**Comment by pafiedor** [comment]
Removed read_output_mult() in d810cf2 < it was an artefact of a previous design of this

Don't think importing pandas here helps enough to justify adding another import, but I do not mind that particularly either.
