### ISSUE TITLE
Refactor iotools.py and stringtools.py to make code consistent with other tools

### ISSUE THREAD

**Issue by cogeorg** [cogeorg/econlib#3]
Right now the code is a bit chaotic. Make it consistent with the design/layout of the other *tools.py. Ideally, make it consistent with best practices for python code.

**Comment by Michael-E-Rose** [comment]
Using my experience from the networkx project, I almost completely rewrote the two files. In particular, I removed redundant documentation as well as code necessary to run the script as standalone.
