### ISSUE TITLE
Local, class, and global variables

### ISSUE THREAD

**Issue by cogeorg** [cogeorg/econlib#9]
One of the most common problems I am having with python is variable scope. Write documentation for each of the Base classes and the infocontagion/ implementation classes where you describe what are the global variables implemented in a class, what are the class variables, and for each method, what are the local variables. Use docstrings to do so.

Basically, I want to be sure that-in particular for the Base classes-all variables are local variables (i.e. those defined within a method and only used within a method, and those referenced by self.*) unless we are sure they should be class- or global variables.

**Comment by pafiedor** [comment]
Docstrings now added to the code in /src/, only nan seems to be a global variables, rest is either class or local.
